[build]
  command = "npm run build"
  publish = "build"
  base = "frontend"

[dev]
  command = "npm run dev"
  targetPort = 3000

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
